version: '2'
services:
  mongo:
    container_name: ms_mongo
    image: mongo:latest
    ports:
      - "27011:27011"
    volumes:
      - "./mongo/db:/data/db"
  user-service:
    build: ./user-service
    container_name: user-service
    environment:
      - loglevel=none
    links:
      - "mongo:mongo"
    volumes:
      - "./user-service:/src/app"
    working_dir: "/src/app"
    ports:
      - "8080:8080"
      - "5858:5858"
    command: npm run start:dev
